login:
    path:     /login
    defaults: { _controller: AppBundle:Security:login }

register:
    path:     /register
    defaults: { _controller: AppBundle:Registration:register }

dashboard:
    path:     /
    defaults: { _controller: AppBundle:Dashboard:index }

profile:
    path:     /profile
    defaults: { _controller: AppBundle:Profile:profile }

new_travel:
    path:     /travel/new
    defaults: { _controller: AppBundle:Travel:newTravel }

show_travel:
    path:     /travel
    defaults: { _controller: AppBundle:Travel:showTravel }

app:
    resource: "@AppBundle/Controller/"
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"